[package]
authors = ["Kuaishou AI Platform PersiaML Team <admin@mail.xrlian.com>"]
edition = "2018"
license = "MIT"
name = "resource_pool"
publish = false
version = "0.1.0"

[dependencies]
arr_macro = "0.1"
persia-libs = {path = "../persia-libs"}
