[package]
name = "persia-speedy"
version = "0.9.0"
authors = ["Jan Bujak <j@exia.io>", "Xiangu Lian <admin@mail.xrlian.com>"]
repository = "https://github.com/NOBLES5E/speedy"
homepage = "https://github.com/NOBLES5E/speedy"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["serialization"]
categories = ["encoding"]
description = "A fast binary serialization framework"
edition = "2018"

[dependencies]
persia-speedy-derive = { version = "= 0.7.3", path = "persia-speedy-derive", optional = true }
chrono = { version = "0.4", optional = true }
smallvec = { version = "1", optional = true }
hashbrown = { version = "0.11.2", optional = true }
bytes = { version = "1.0", optional = true }
indexmap = { version = "1.6", optional = true }
ndarray = { version = "0.15.3", optional = true }
tinystr = { version = "0.7", optional = true }
half = { version = "1.6", features = ["alloc"] }

[dev-dependencies]
quickcheck = "1.0.3"

# [profile.release]
# panic = "abort"

# [workspace]
# members = [".", "persia-speedy-derive", "static-tests"]

[features]
default = ["persia-speedy-derive", "chrono", "smallvec", "hashbrown", "bytes", "indexmap", "ndarray", "tinystr"]
external_doc = []

[package.metadata.docs.rs]
features = ["external_doc"]
