version: "3.3"
services:
        torch_serve:
            env_file:
                - adult_income/.test_env
            environment:
                JOB_ID: 1
            image: persiaml-infer-test:latest
            command: bash -c "/workspace/launch_ts.sh server"
            volumes:
                - ./adult_income:/workspace
            deploy:
                endpoint_mode: dnsrr

        client:
            env_file:
                - adult_income/.test_env
            environment:
                JOB_ID: 1
            image: persiaml-infer-test:latest
            command: bash -c "/workspace/launch_ts.sh client"
            volumes:
                - ./adult_income:/workspace
            deploy:
                endpoint_mode: dnsrr

        middleware:
            env_file:
                - adult_income/.test_env
            environment:
                JOB_ID: 1
            image: persiaml-infer-test:latest
            command: persia_launcher middleware --embedding-config /workspace/config/embedding_config.yml --global-config /workspace/config/global_config.yml
            volumes:
                - ./adult_income:/workspace
            deploy:
                endpoint_mode: dnsrr

        server:
            env_file:
                - adult_income/.test_env
            environment:
                JOB_ID: 1
            image: persiaml-infer-test:latest
            command: persia_launcher server --embedding-config /workspace/config/embedding_config.yml --global-config /workspace/config/global_config.yml
            volumes:
                - ./adult_income:/workspace
            deploy:
                endpoint_mode: dnsrr