[package]
authors = ["Kuaishou AI Platform PersiaML Team <admin@mail.xrlian.com>"]
edition = "2018"
license = "MIT"
name = "persia-rpc"
publish = false
version = "0.1.0"

[dependencies]
persia-libs = {path = "../../persia-libs"}
persia-speedy = "0.9"
snafu = "0.6"
tracing = "0.1"
