{
 "title": "Persia Training",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "staleness",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "staleness{}" }
   ]
  },
  {
   "title": "num pending batches",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "num_pending_batches{}" }
   ]
  },
  {
   "title": "batch unique indices rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "batch_unique_indices_rate{}" }
   ]
  },
  {
   "title": "index miss ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "index_miss_ratio{}" }
   ]
  },
  {
   "title": "index miss count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "rate(index_miss_count[1m])" }
   ]
  },
  {
   "title": "gradient id miss count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(gradient_id_miss_count[1m])"
    }
   ]
  },
  {
   "title": "lookup mixed batch time cost",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lookup_mixed_batch_time_cost_sec{}"
    }
   ]
  },
  {
   "title": "lookup create requests time cost",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lookup_create_requests_time_cost_sec{}"
    }
   ]
  },
  {
   "title": "lookup rpc time cost",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "lookup_rpc_time_cost_sec{}" }
   ]
  },
  {
   "title": "update gradient time cost",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "update_gradient_time_cost_sec{}"
    }
   ]
  },
  {
   "title": "summation time cost",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "summation_time_cost_sec{}" }
   ]
  },
  {
   "title": "lookup batched time cost",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "lookup_batched_time_cost_sec{}" }
   ]
  }
 ]
}