# nn_worker: persia-launcher nn-worker train.py --nproc-per-node=$NPROC_PER_NODE --node-rank=0 --nnodes=1
# data_loader: python3 data_loader.py && cat
# embedding_server: persia-launcher embedding-parameter-server --embedding-config config/embedding_config.yml --global-config config/global_config.yml --replica-index $REPLICA_INDEX --replica-size $REPLICA_SIZE
# embedding_worker: persia-launcher embedding-worker --embedding-config config/embedding_config.yml --global-config config/global_config.yml --replica-index $REPLICA_INDEX --replica-size $REPLICA_SIZE
# nats_server: nats-server 


nn_worker: persia-launcher nn-worker train.py --nproc-per-node=1 --node-rank=0 --nnodes=1
data_loader: persia-launcher data-loader data_loader.py && cat
embedding_server: persia-launcher embedding-parameter-server --embedding-config config/embedding_config.yml --global-config config/global_config.yml --replica-index 1 --replica-size 1
embedding_worker: persia-launcher embedding-worker --embedding-config config/embedding_config.yml --global-config config/global_config.yml --replica-index 1 --replica-size 1
nats_server: nats-server 