steps:
  - label: "Build docker ci image for latest persiaml framework"
    command: docker build e2e --build-arg GITHUB_TOKEN=$$GITHUB_TOKEN --build-arg USE_CUDA=1 -t persiaml-test:latest

  - label: "Add executive permission to script"
    command: chmod +x -R e2e/adult_income

  - wait
  - label: "launch middleware"
    plugins:
      - docker-compose#v3.8.0::
          config: "e2e/docker-compose.yml"
          run: middleware

  - label: "launch embed-server"
    plugins:
      - docker-compose#v3.8.0::
          config: "e2e/docker-compose.yml"
          run: server
  - label: "launch trainer"
    plugins:
      - docker-compose#v3.8.0::
          config: "e2e/docker-compose.yml"
          run: trainer

  - label: "launch compose"
    plugins:
      - docker-compose#v3.8.0::
          config: "e2e/docker-compose.yml"
          run: data_compose

  - wait
