steps:
  - label: "Build docker ci image for latest persiaml framework"
    command: docker build --build-arg USE_CUDA=1 -t persiaml-test:latest -f docker/persia-cuda-runtime/Dockerfile .

  - label: "Build docker ci image with inference environment for latest persiaml framework"
    command: docker build --build-arg USE_CUDA=1 -t persiaml-infer-test:latest -f docker/persia-inference-runtime/Dockerfile .

  - wait

  - label: "launch train eval e2e test"
    key: "train-eval"
    plugins:
      - docker-compose#v3.8.0::
          config: "e2e/train/docker-compose.yml"
          run: trainer
          graceful-shutdown: true

  - label: "launch infer e2e test"
    key: "infer"
    plugins:
      - docker-compose#v3.8.0::
          config: "e2e/infer/docker-compose.yml"
          run: trainer
          graceful-shutdown: true


  - label: "upload the latest cuda-runtime image"
    branches: "main"
    command: 
      - docker login -u $$DOCKER_USER -p $$DOCKER_TOKEN
      - docker tag persiaml-test:latest persiaml/persia-cuda-runtime:latest 
      - docker push persiaml/persia-cuda-runtime:latest 
