steps:
  - label: "Build docker ci image for latest persiaml framework"
    command: docker build --build-arg USE_CUDA=1 -t persiaml-test:latest .

  - wait

  - label: "launch e2e test"
    key: "e2e-test"
    plugins:
      - docker-compose#v3.8.0::
          config: "e2e/docker-compose.train.yml"
          run: trainer
          graceful-shutdown: true
      - docker-compose#v3.8.0::
          config: "e2e/docker-compose.infer.yml"
          run: torch_serve
          graceful-shutdown: true


  - label: "upload the latest cuda-runtime image"
    branches: "main"
    command: 
      - docker login -u $$DOCKER_USER -p $$DOCKER_TOKEN
      - docker tag persiaml-test:latest persiaml/persia-cuda-runtime:latest 
      - docker push persiaml/persia-cuda-runtime:latest 
