steps:
  - label: "Build docker ci image for latest persiaml framework"
    command: docker build e2e --build-arg GITHUB_TOKEN=$$GITHUB_TOKEN --build-arg USE_CUDA=1 -t persiaml-test:latest

  - label: "Add executive permission to script"
    command: chmod +x -R e2e/adult_income

  - label: "Download dataset and preprocessed the corresponding data"
    command: "chmod +x /workspace//workspace/download_data.sh && /workspace/download_data.sh"
    plugins:
      - docker#v3.8.0:
          always-pull: true
          run: download_data
          image: "persiaml/persia-ci:latest"
          volumes:
            - "e2e/adult_income:/workspace"
  - wait
  - label: "launch trainer"
    plugins:
      - docker-compose#v3.8.0::
          config: "e2e/docker-compose.yml"
          network: "test-e2e"
          run: trainer

  - label: "launch compose"
    plugins:
      - docker-compose#v3.8.0::
          config: "e2e/docker-compose.yml"
          network: "test-e2e"
          run: data_compose

  - label: "launch middleware"
    plugins:
      - docker-compose#v3.8.0::
          config: "e2e/docker-compose.yml"
          network: "test-e2e"
          run: middleware

  - label: "launch embed-server"
    plugins:
      - docker-compose#v3.8.0::
          config: "e2e/docker-compose.yml"
          network: "test-e2e"
          run: server
  - wait
