steps:
  - label: "Build docker ci image for latest persiaml framework(CPU)"
    command: make build_cuda_runtime_image 

  - label: "Build docker ci image for latest persiaml framework(GPU)"
    command: make build_cpu_runtime_image 

  - wait

  - label: "launch e2e gpu test"
    key: "e2e-gpu-test"
    env:
      IMAGE_TYPE: "cuda"
    plugins:
      - docker-compose#v3.8.0:
          config: "e2e/docker-compose.train.yml"
          run: trainer
          propagate-uid-gid: true
          env:
            - BUILDKITE_STEP_ID
          graceful-shutdown: true
      - docker-compose#v3.8.0:
          config: "e2e/docker-compose.infer.yml"
          run: torch_serve
          propagate-uid-gid: true
          env:
            - BUILDKITE_STEP_ID
          graceful-shutdown: true
  # TODO: add bagua testcase
  - label: "launch e2e cpu test"
    key: "e2e-cpu-test"
    env:
      IMAGE_TYPE: "cpu"
    plugins:
      - docker-compose#v3.8.0:
          config: "e2e/docker-compose.train.yml"
          run: trainer
          propagate-uid-gid: true
          env:
            - BUILDKITE_STEP_ID
          graceful-shutdown: true
      - docker-compose#v3.8.0:
          config: "e2e/docker-compose.infer.yml"
          run: torch_serve
          propagate-uid-gid: true
          env:
            - BUILDKITE_STEP_ID
          graceful-shutdown: true

  - wait  

  - label: "clear workspace, e2e folder will be remove after thie step"
    key: "clear"
    command: echo "finish e2e test"

  - label: "build and upload the latest ci image"
    branches: "main"
    command: 
      - docker login -u $$DOCKER_USER -p $$DOCKER_TOKEN
      - ./buildkite/upload_docker_image.sh