steps:
  - label: "Build docker ci image for latest persiaml framework(CPU)"
    command: IMAGE_TAG=$BUILDKITE_PIPELINE_ID make build_cuda_runtime_image -e

  - label: "Build docker ci image for latest persiaml framework(GPU)"
    command: IMAGE_TAG=$BUILDKITE_PIPELINE_ID make build_cpu_runtime_image -e

  - wait

  - label: "launch e2e gpu test"
    key: "e2e-gpu-test"
    env:
      IMAGE_TYPE: "cuda"
    plugins:
      - docker-compose#v3.8.0:
          config: "e2e/docker-compose.train.yml"
          run: nn_worker
          graceful-shutdown: true
      - docker-compose#v3.8.0:
          config: "e2e/docker-compose.infer.yml"
          run: torch_serve
          graceful-shutdown: true

  - label: "launch e2e cpu test"
    key: "e2e-cpu-test"
    env:
      IMAGE_TYPE: "cpu"
    plugins:
      - docker-compose#v3.8.0:
          config: "e2e/docker-compose.train.yml"
          run: nn_worker
          graceful-shutdown: true
      - docker-compose#v3.8.0:
          config: "e2e/docker-compose.infer.yml"
          run: torch_serve
          graceful-shutdown: true

  - label: "launch k8s e2e test"
    pre-command: .buildkite/script/nats_operator_process.sh apply
    command:
      - docker run --rm -it -v $BUILDKITE_BUILD_CHECKOUT_PATH/e2e/cache:/cache persia-cpu-runtime:${BUILDKITE_PIPELINE_ID} bash -c "cp /opt/conda/lib/python3.8/site-packages/persia/e2e /cache"
      - export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
      - $BUILDKITE_BUILD_CHECKOUT_PATH/e2e/cache/e2e
    post-command: .buildkite/script/nats_operator_process.sh delete

  - wait

  - label: "upload docker image"
    branches: "main"
    command:
      - docker login -u $$DOCKER_USER -p $$DOCKER_TOKEN
      - .buildkite/script/docker_image_process.sh upload

  - wait
  
  - label: "remove docker image"
    command: .buildkite/script/docker_image_process.sh remove
