[package]
authors = ["Kuaishou AI Platform PersiaML Team <admin@mail.xrlian.com>"]
edition = "2018"
license = "MIT"
name = "persia-scheduled-thread-pool"
publish = false
version = "0.1.0"

[dependencies]
persia-libs = {path = "../persia-libs"}
scheduled-thread-pool = "0.2"
