nn_worker: persia_launcher nn-worker $CODE_BASE/train.py --gpu-num=$GPU_NUM --node-rank=0 --nnodes=1
data_loader: python3.6 $CODE_BASE/data_loader.py && sleep infinity
embedding_server: persia_launcher embedding-parameter-server --embedding-config $CODE_BASE/config/embedding_config.yml --global-config $CODE_BASE/config/global_config.yml --replica-index $REPLICA_INDEX --replica-size $REPLICA_SIZE
embedding_worker: persia_launcher embedding-worker --embedding-config $CODE_BASE/config/embedding_config.yml --global-config $CODE_BASE/config/global_config.yml --replica-index $REPLICA_INDEX --replica-size $REPLICA_SIZE
nats_server: nats-server 
