apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: trainer
  name: trainer
spec:
  serviceName: trainer
  replicas: 8
  selector:
    matchLabels:
      service: trainer
  template:
    metadata:
      labels:
        service: trainer
    spec:
      containers:
        - args:
            - /workspace/launch.sh
            - trainer
          image: persiaml/persia-cuda-runtime:latest
          resources:
            requests:
              memory: "600Gi"
              cpu: "80"
              nvidia.com/gpu: 8
            limits:
              memory: "600Gi"
              cpu: "80"
              nvidia.com/gpu: 8
          name: trainer
          env:
            - name: REPLICA_SIZE
              value: "8"
            - name: NPROC_PER_NODE
              value: "8"
            - name: PERSIA_NATS_IP
              value: nats://persia-nats-service:4222
          imagePullPolicy: Always

status:
  replicas: 8

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: data-compose
  name: data-compose
spec:
  serviceName: data-compose
  replicas: 240
  selector:
    matchLabels:
      service: data-compose
  template:
    metadata:
      labels:
        service: data-compose
    spec:
      containers:
        - args:
            - /workspace/launch.sh
            - datacompose
          image: persiaml/persia-cuda-runtime:latest
          resources:
            requests:
              memory: "12Gi"
              cpu: "1"
            limits:
              memory: "12Gi"
              cpu: "1"
          name: data-compose
          env:
            - name: REPLICA_SIZE
              value: "240"
            - name: PERSIA_NATS_IP
              value: nats://persia-nats-service:4222
          imagePullPolicy: Always
status:
  replicas: 240

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: middleware
  name: middleware
spec:
  serviceName: middleware
  replicas: 100
  selector:
    matchLabels:
      service: middleware
  template:
    metadata:
      labels:
        service: middleware
    spec:
      containers:
        - args:
            - /workspace/launch.sh
            - middleware
          image: persiaml/persia-cuda-runtime:latest
          resources:
            requests:
              memory: "100Gi"
              cpu: "28"
            limits:
              memory: "100Gi"
              cpu: "28"
          name: middleware
          env:
            - name: REPLICA_SIZE
              value: "100"
            - name: PERSIA_NATS_IP
              value: nats://persia-nats-service:4222
          imagePullPolicy: Always
status:
  replicas: 100

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: emb-server
  name: emb-server
spec:
  serviceName: emb-server
  replicas: 120
  selector:
    matchLabels:
      service: emb-server
  template:
    metadata:
      labels:
        service: emb-server
    spec:
      containers:
        - args:
            - /workspace/launch.sh
            - embserver
          image: persiaml/persia-cuda-runtime:latest
          resources:
            requests:
              memory: "2500Gi"
              cpu: "80"
            limits:
              memory: "2500Gi"
              cpu: "80"
          name: emb-server
          env:
            - name: REPLICA_SIZE
              value: "120"
            - name: PERSIA_NATS_IP
              value: nats://persia-nats-service:4222
          imagePullPolicy: Always
status:
  replicas: 120

---

apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "persia-nats-service"
spec:
  size: 60
  natsConfig:
    maxPayload: 52428800

  resources:
    requests:
      memory: "32Gi"
      cpu: "4"
    limits:
      memory: "32Gi"
      cpu: "4"