[package]
authors = ["Kuaishou AI Platform PersiaML Team <zhuxuefeng@kuaishou.com>"]
edition = "2018"
license = "MIT"
name = "persia-model-manager"
publish = false
version = "0.1.0"

[dependencies]
persia-embedding-config = {path = "../persia-embedding-config"}
persia-embedding-holder = {path = "../persia-embedding-holder"}
persia-libs = {path = "../persia-libs"}
persia-speedy = {path = "../persia-speedy"}
persia-storage = {path = "../persia-storage"}
