[package]
authors = ["Kuaishou AI Platform PersiaML Team <admin@mail.xrlian.com>"]
edition = "2018"
name = "persia-common-benchmark"
version = "0.1.0"

#[lib]
#bench = false

[dev-dependencies]
bincode = "1"
criterion = "0.3"
criterion-macro = "0.3"
persia-speedy = "0.9"
serde = {version = "1", features = ["derive"]}
smallvec = "1"
tinystr = "0.4"

[[bench]]
name = "memcpy"
#harness = false

[[bench]]
name = "serialize_inf_request"
#harness = false
