version: "3.3"
services:
    torch_serve:
        env_file:
            - adult_income/.test.env
        image: persia-${IMAGE_TYPE}-runtime:${BUILDKITE_PIPELINE_ID}
        command: bash -c "/workspace/launch_ts.sh"
        volumes:
            - ./adult_income:/workspace
            - ./cache:/cache
            - /data/adult_income:/data/
        deploy:
            endpoint_mode: dnsrr
        depends_on:
            - embedding_worker
            - embedding_parameter_server

    embedding_worker:
        env_file:
            - adult_income/.test.env
        image: persia-${IMAGE_TYPE}-runtime:${BUILDKITE_PIPELINE_ID}
        command: >
            bash -c "persia-launcher embedding-worker --embedding-config /workspace/config/embedding_config.yml
            --global-config /workspace/config/global_config_infer.yml --replica-index 0 --replica-size 1"
        volumes:
            - ./adult_income:/workspace
            - ./cache:/cache
        deploy:
            endpoint_mode: dnsrr
        depends_on:
            - embedding_parameter_server

    embedding_parameter_server:
        env_file:
            - adult_income/.test.env
        image: persia-${IMAGE_TYPE}-runtime:${BUILDKITE_PIPELINE_ID}
        command: >
            bash -c "persia-launcher embedding-parameter-server --embedding-config /workspace/config/embedding_config.yml
            --global-config /workspace/config/global_config_infer.yml --replica-index 0 --replica-size 1"
        volumes:
            - ./adult_income:/workspace
            - ./cache:/cache
        deploy:
            endpoint_mode: dnsrr