version: "3.3"
services:
        torch_serve:
            env_file:
                - adult_income/.test_env
            environment:
                JOB_ID: 1
            image: persiaml-infer-test:latest
            command: bash -c "/workspace/launch_ts.sh"
            volumes:
                - ./adult_income:/workspace
            deploy:
                endpoint_mode: dnsrr

        middleware:
            env_file:
                - adult_income/.test_env
            environment:
                JOB_ID: 1
            image: persiaml-infer-test:latest
            command: mkdir -p /workspace/logs/ && persia_launcher middleware --embedding-config /workspace/config/embedding_config.yml --global-config /workspace/config/global_config_infer.yml > /workspace/logs/middleware.log
            volumes:
                - ./adult_income:/workspace
            deploy:
                endpoint_mode: dnsrr

        emb_server:
            env_file:
                - adult_income/.test_env
            environment:
                JOB_ID: 1
            image: persiaml-infer-test:latest
            command: mkdir -p /workspace/logs/ && persia_launcher server --embedding-config /workspace/config/embedding_config.yml --global-config /workspace/config/global_config_infer.yml > /workspace/logs/emb_server.log
            volumes:
                - ./adult_income:/workspace
            deploy:
                endpoint_mode: dnsrr