version: "3.3"
services:
        data_compose:
            env_file:
                - adult_income/.test_env
            environment:
                JOB_ID: 1
            depends_on:
                - trainer
                - middleware
            image: persiaml-test:latest
            command: bash -c "/workspace/launch_compose.sh /workspace/data_compose.py"
            networks:
                - e2e-test
            volumes:
                - ./adult_income:/workspace
                - /data/adult_income:/data/

        trainer:
            env_file:
                - adult_income/.test_env
            environment:
                JOB_ID: 1
                NCCL_SOCKET_IFNAME: eth0
                GPU_NUM: 1
            image: persiaml-test:latest
            command:  bash -c "/workspace/launch_persia.sh /workspace/train.py"
            networks:
                - e2e-test
            volumes:
                - ./adult_income:/workspace
                - /data/adult_income:/data/

        middleware:
            env_file:
                - adult_income/.test_env
            environment:
                JOB_ID: 1
            depends_on:
                - server
            image: persiaml-test:latest
            command: bash -c "/workspace/launch_middleware.sh"
            networks:
                - e2e-test
            volumes:
                - ./adult_income:/workspace

        server:
            env_file:
                - adult_income/.test_env
            environment:
                JOB_ID: 1
            image: persiaml-test:latest
            command: bash -c "/workspace/launch_server.sh"
            networks:
                - e2e-test
            volumes:
                - ./adult_income:/workspace
networks:
    e2e-test: