apiVersion: persia.com/v1
kind: PersiaJob
metadata:
  name: test
  namespace: default
spec:
  globalConfigPath: /workspace/config/global_config_train.yml
  embeddingConfigPath: /workspace/config/embedding_config.yml
  trainerPyEntryPath: /workspace/train.py
  dataLoaderPyEntryPath: /workspace/data_compose.py
  volumes:
    - name: data
      hostPath:
        path: /data/adult_income/
        type: Directory
    # - name: resources
    #   hostPath:
    #     path: ../resources/
    #     type: Directory
    - name: workspace
      hostPath:
        path: /home/aip-persia-team/zhuxuefeng/PersiaML/PersiaML/e2e/adult_income/
        type: Directory

  embeddingServer:
    replicas: 1
    resources:
      limits:
        memory: "24Gi"
        cpu: "4"
    volumeMounts:
      - name: workspace
        mountPath: /workspace/

  middlewareServer:
    replicas: 1
    resources:
      limits:
        memory: "24Gi"
        cpu: "4"
    volumeMounts:
      - name: workspace
        mountPath: /workspace/

  trainer:
    replicas: 1
    nprocPerNode: 1
    resources:
      limits:
        memory: "24Gi"
        cpu: "12"
        nvidia.com/gpu: "1"
    volumeMounts:
      - name: workspace
        mountPath: /workspace/

  dataloader:
    replicas: 1
    resources:
      limits:
        memory: "8Gi"
        cpu: "1"
    volumeMounts:
      - name: workspace
        mountPath: /workspace/
      - name: data
        mountPath: /data/
        read_only: true