apiVersion: persia.com/v1
kind: PersiaJob
metadata:
  name: adult-income
  namespace: default
spec:
  globalConfigPath: /workspace/config/global_config_train.yml
  embeddingConfigPath: /workspace/config/embedding_config.yml
  trainerPyEntryPath: /workspace/train.py
  dataLoaderPyEntryPath: /workspace/data_compose.py
  volumes:
    - name: data
      hostPath:
        path: /nfs/general/data/adult_income/
        type: Directory
    - name: workspace
      hostPath:
        path: /nfs/general/PersiaML/e2e/adult_income/
        type: Directory
    - name: persia-dev
      hostPath:
        path: /nfs/general/zhuxuefeng/persia-dev/
        type: Directory
  env:
    - name: EVAL_CHECKPOINT_DIR
      value: /workspace/eval_checkpoint/
    - name: INFER_CHECKPOINT_DIR
      value: /workspace/infer_checkpoint/
    - name: RESULT_FILE_PATH
      value: /workspace/result.json
    - name: PERSIA_NATS_IP
      value: nats://persia-nats-service:4222
    - name: PERSIA_DEV_PATH
      value: /persia-dev/
    - name: PERSIA_DEV_PYTHONPATH
      value: /persia-dev/
    - name: DEBUG
      value: "1"

  embeddingServer:
    replicas: 1
    resources:
      limits:
        memory: "24Gi"
        cpu: "4"
    volumeMounts:
      - name: workspace
        mountPath: /workspace/
      - name: persia-dev
        mountPath: /persia-dev/

  middlewareServer:
    replicas: 1
    resources:
      limits:
        memory: "24Gi"
        cpu: "4"
    volumeMounts:
      - name: workspace
        mountPath: /workspace/
      - name: persia-dev
        mountPath: /persia-dev/

  trainer:
    replicas: 1
    nprocPerNode: 1
    resources:
      limits:
        memory: "24Gi"
        cpu: "12"
        nvidia.com/gpu: "1"
    volumeMounts:
      - name: workspace
        mountPath: /workspace/
      - name: data
        mountPath: /data/
        read_only: true
      - name: persia-dev
        mountPath: /persia-dev/
    env:
      - name: CUBLAS_WORKSPACE_CONFIG
        value: :4096:8

  dataloader:
    replicas: 1
    resources:
      limits:
        memory: "8Gi"
        cpu: "1"
    volumeMounts:
      - name: workspace
        mountPath: /workspace/
      - name: data
        mountPath: /data/
        read_only: true
      - name: persia-dev
        mountPath: /persia-dev/

---

apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "persia-nats-service"
spec:
  size: 1
  natsConfig:
    maxPayload: 52428800
  resources:
    limits:
      memory: "8Gi"
      cpu: "2" 