apiVersion: persia.com/v1
kind: PersiaJob
metadata:
  name: test
  namespace: default
spec:
  globalConfigPath: /workspace/config/global_config_train.yml
  embeddingConfigPath: /workspace/config/embedding_config.yml
  trainerPyEntryPath: /workspace/train.py
  dataLoaderPyEntryPath: /workspace/data_compose.py
  volumes:
    - name: data
      hostPath:
        path: /data/adult_income/
        type: Directory
    # - name: resources
    #   hostPath:
    #     path: ../resources/
    #     type: Directory
    - name: workspace
      hostPath:
        path: /home/aip-persia-team/zhuxuefeng/PersiaML/PersiaML/e2e/adult_income/
        type: Directory
  env:
    - name: EVAL_CHECKPOINT_DIR
      value: /workspace/eval_checkpoint/
    - name: INFER_CHECKPOINT_DIR
      value: /workspace/infer_checkpoint/
    - name: HDFS_CHECKPOINT_DIR
      value: hdfs://hdfsserver:9000//workspace/hdfs_checkpoint/
    - name: RESULT_FILE_PATH
      value: /workspace/result.json
    - name: PERSIA_NATS_IP
      value: nats://persia-nats-service:4222


  embeddingServer:
    replicas: 1
    resources:
      limits:
        memory: "24Gi"
        cpu: "4"
    volumeMounts:
      - name: workspace
        mountPath: /workspace/

  middlewareServer:
    replicas: 1
    resources:
      limits:
        memory: "24Gi"
        cpu: "4"
    volumeMounts:
      - name: workspace
        mountPath: /workspace/

  trainer:
    replicas: 1
    nprocPerNode: 1
    resources:
      limits:
        memory: "24Gi"
        cpu: "12"
        nvidia.com/gpu: "1"
    volumeMounts:
      - name: workspace
        mountPath: /workspace/
      - name: data
        mountPath: /data/
        read_only: true

  dataloader:
    replicas: 1
    resources:
      limits:
        memory: "8Gi"
        cpu: "1"
    volumeMounts:
      - name: workspace
        mountPath: /workspace/
      - name: data
        mountPath: /data/
        read_only: true

---

apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "persia-nats-service"
spec:
  size: 1
  natsConfig:
    maxPayload: 52428800
  resources:
    limits:
      memory: "8Gi"
      cpu: "2" 