apiVersion: persia.com/v1
kind: PersiaJob
metadata:
  name: test
  namespace: default
spec:
  global_config_path: /workspace/config/global_config_train.yml
  embedding_config_path: /workspace/config/embedding_config.yml
  trainer_py_entry_path: /workspace/train.py
  data_loader_py_entry_path: /workspace/data_compose.py
  volumes:
    - name: data
      hostPath:
        path: /data/adult_income/
        type: Directory
    # - name: resources
    #   hostPath:
    #     path: ../resources/
    #     type: Directory
    - name: workspace
      hostPath:
        path: ./adult_income/
        type: Directory

  embedding_server:
    replicas: 1
    resources:
      limits:
        memory: "24Gi"
        cpu: "4"
    volume_mounts:
      - name: workspace
        mountPath: /workspace/

  middleware_server:
    replicas: 1
    resources:
      limits:
        memory: "24Gi"
        cpu: "4"
    volume_mounts:
      - name: workspace
        mountPath: /workspace/

  trainer:
    replicas: 1
    nproc_per_node: 1
    resources:
      limits:
        memory: "24Gi"
        cpu: "12"
        nvidia.com/gpu: "1"
    volume_mounts:
      - name: workspace
        mountPath: /workspace/

  dataloader:
    replicas: 1
    resources:
      limits:
        memory: "8Gi"
        cpu: "1"
    volume_mounts:
      - name: workspace
        mountPath: /workspace/
      - name: data
        mountPath: /data/
        read_only: true