version: "3.2"
services:
  persia_nats_service:
    image: nats:latest
    deploy:
      replicas: 1
          
  data_loader:
    env_file:
      - .docker.env
    depends_on:
      - nn_worker
      - embedding_worker
      - persia_nats_service
    image: persiaml/persia-cuda-runtime:latest
    command: persia-launcher data-loader --replica-index 0 --replica-size 1
    volumes:
      - type: bind
        source: .
        target: /workspace
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nn_worker:
    env_file:
      - .docker.env
    environment:
      NCCL_SOCKET_IFNAME: eth0
      CUBLAS_WORKSPACE_CONFIG: :4096:8
    image: persiaml/persia-cuda-runtime:latest
    command: persia-launcher nn-worker --nproc-per-node 1 --nnodes 1 --node-rank 0
    volumes:
      - type: bind
        source: .
        target: /workspace
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  embedding_worker:
    env_file:
      - .docker.env
    depends_on:
      - embedding_parameter_server
    image: persiaml/persia-cuda-runtime:latest
    command: > 
      bash -c "persia-launcher embedding-worker --embedding-config $$PERSIA_EMBEDDING_CONFIG
      --global-config $$PERSIA_GLOBAL_CONFIG --replica-index 0 --replica-size 1"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: .
        target: /workspace

  embedding_parameter_server:
    env_file:
      - .docker.env
    image: persiaml/persia-cuda-runtime:latest
    command: > 
      bash -c "persia-launcher embedding-parameter-server --embedding-config $$PERSIA_EMBEDDING_CONFIG
      --global-config $$PERSIA_GLOBAL_CONFIG --replica-index 0 --replica-size 1"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: .
        target: /workspace