feature_index_prefix_bit: 12
slots_config:
  workclass:
    dim: 8
  education:
    dim: 8
  marital_status:
    dim: 8
  occupation:
    dim: 8
  relationship:
    dim: 8
  race:
    dim: 8
  gender:
    dim: 8
  native_country:
    dim: 8
feature_groups: {}
