PersiaEmbeddingServerConfig:
  job_type: train
  capacity: 100000000
  num_hashmap_internal_shards: 128
  num_embedding_io_workers: 4
  enable_incremental_update: false
  incremental_buffer_size: 5000000
  incremental_dir: /tmp/persia_inc/
  incremental_channel_capacity: 1000
PersiaMetricsConfig:
  enable_metrics: true
  push_interval_seconds: 10