[package]
authors = ["Kuaishou AI Platform PersiaML Team <admin@mail.xrlian.com>"]
edition = "2018"
license = "MIT"
name = "persia-rpc-macro"
publish = false
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1.0"
reqwest = {version = "0.11", default-features = false, features = ["native-tls-vendored"]}
syn = {version = "1.0", features = ["full"]}
