[package]
authors = ["Kuaishou AI Platform PersiaML Team <admin@mail.xrlian.com>"]
edition = "2018"
name = "persia-message-queue"
version = "0.1.0"
license = "MIT"

[dependencies]
persia-futures = {path = "../persia-futures"}
hyper = {version = "0.14", features = ["full"]}
pyo3 = "0.13.2"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.2.5"
url = "2.1"
