[package]
authors = ["Kuaishou AI Platform PersiaML Team <admin@mail.xrlian.com>"]
edition = "2018"
license = "MIT"
name = "persia-message-queue"
version = "0.1.0"

[dependencies]
hyper = {version = "0.14", features = ["full"]}
persia-libs = {path = "../persia-libs"}
url = "2.1"
