[package]
authors = ["Kuaishou AI Platform PersiaML Team <admin@mail.xrlian.com>"]
edition = "2018"
license = "MIT"
name = "persia-embedding-config"
publish = false
version = "0.1.0"

[dependencies]
get_if_addrs = "0.5.3"
local_ipaddress = "0.1.3"
num-traits = "0.2.17"
persia-libs = {path = "../persia-libs"}
persia-speedy = {path = "../persia-speedy"}
