on: push

name: rust pypi publish

jobs:
  publish:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Install latest stable rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Python packaging dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: cd rust && python -m build -s
    - name: Publish a Python distribution to PyPI
      if: github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: rust
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: rust
