name: rust fmt

on: push

jobs:
  format:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
            override: true
      - name: rust-rustfmt-check
        uses: mbrobbel/rustfmt-check@0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path rust/Cargo.toml --all
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - name: Run tests
        run: cd rust/ && cargo test --verbose
